FROM node:20-alpine AS app-builder
WORKDIR /app-frontend
COPY package*.json ./
RUN npm install --ignore-scripts
RUN npm install -g @angular/cli
COPY . .
RUN npm run build

FROM nginx:latest AS frontend
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=app-builder /app-frontend/dist/billzy/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]